export const FETCH_REPOS = 'FETCH_REPOS'
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS'
export const GET_REPOS_FAILURE = 'GET_REPOS_FAILURE'

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES'
export const ACTIVITIES_SUCCESS = 'ACTIVITIES_SUCCESS'
export const ACTIVITIES_FAILURE = 'ACTIVITIES_FAILURE'
